export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAILURE = "USER_LOADED_FAILURE";

export const WATCHLIST_LOADED = "WATCHLIST_LOADED";
export const WATCHLIST_LOADED_FAILED = "WATCHLIST_LOADED_FAILED";

export const ADD_TO_WATCHLIST_SUCCESS = "ADD_TO_WATCHLIST_SUCCESS";
export const ADD_TO_WATCHLIST_FAILED = "ADD_TO_WATCHLIST_FAILED";

export const REMOVE_FROM_WATCHLIST_SUCCESS = "REMOVE_FROM_WATCHLIST_SUCCESS";
export const REMOVE_FROM_WATCHLIST_FAILED = "REMOVE_FROM_WATCHLIST_FAILED";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const RATE_MOVIE_SUCCESS = "RATE_MOVIE_SUCCESS";
export const RATE_MOVIE_FAILED = "RATE_MOVIE_FAILED";
